### ISSUE TITLE
BUG? evaluate.py CANNOT GENERATE FROM LOCAL STYLE WEIGHTS?

### ISSUE THREAD

**Issue by mythicalBOB** [PairCustomization/PairCustomization#5]
evaluate.py: 
`lora_path_name = "./example_loras/lora-dog-digital-art-style.safetensors"`

### _Above_ line seem to only take in huggingface 'repo_name' or 'namespace/repo_name' according to error _below_, but not local file?
Is there a way around this?

### ERROR:
`(venv) root@b9408ada9e0f:/workspace/PairCustomization# python evaluation_scripts/evaluate.py
/workspace/PairCustomization/venv/lib/python3.10/site-packages/diffusers/models/dual_transformer_2d.py:20: FutureWarning: `DualTransformer2DModel` is deprecated and will be removed in version 0.29. Importing `DualTransformer2DModel` from `diffusers.models.dual_transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel`, instead.
  deprecate("DualTransformer2DModel", "0.29", deprecation_message)
/workspace/PairCustomization/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloadsalways resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  8.43it/s]
Traceback (most recent call last):
  File "/workspace/PairCustomization/evaluation_scripts/evaluate.py", line 46, in <module>
    run_evaluation()
  File "/workspace/PairCustomization/evaluation_scripts/evaluate.py", line 19, in run_evaluation
    SDXL_pipeline.load_lora_weights(lora_path_name, adapter_name="style_weights")
  File "/workspace/PairCustomization/venv/lib/python3.10/site-packages/diffusers/loaders/lora.py", line 1350, in load_lora_weights
    state_dict, network_alphas = self.lora_state_dict(
  File "/workspace/PairCustomization/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/workspace/PairCustomization/venv/lib/python3.10/site-packages/diffusers/loaders/lora.py", line 242, in lora_state_dict
    weight_name = cls._best_guess_weight_name(
  File "/workspace/PairCustomization/venv/lib/python3.10/site-packages/diffusers/loaders/lora.py", line 325, in _best_guess_weight_name
    files_in_repo = model_info(pretrained_model_name_or_path_or_dict).siblings
  File "/workspace/PairCustomization/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/workspace/PairCustomization/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './example_loras/lora-dog-digital-art-style.safetensors'. Use `repo_type` argument if needed.`

### Thanks

**Comment by christianchartier** [comment]
Was this solved? If so, how?
